version: '3'

networks:
  laravel:
    driver: bridge


services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:
      # config share project folder
      - ./src/intern-training-khuongpham:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4043:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: Mysql
    networks:
      - laravel

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes: 
      - ./src/intern-training-khuongpham:/var/www/html
      - type: bind
        source: ./src/intern-training-khuongpham/storage/app/images
        target: /var/www/html/public/images
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:5.1
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel    
    # server: mysql // username: root // password: 123456
    
  redis:
    image: 'bitnami/redis:latest'
    container_name: db_cache
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  
    networks:
      - laravel                                    